### ISSUE TITLE
本地部署运行不起来........

### ISSUE THREAD

**Issue by jjeejj** [YMFE/json-schema-editor-visual#1]
按照步骤运行
`npm install && npm run start` 后

打开`http://127.0.0.1:8082/` 是可以的

![jietu20180316-232747](https://user-images.githubusercontent.com/15176971/37529281-b4ae8bc8-2971-11e8-9867-22fe687545cd.jpg)

但是点击`index.html`就没有反应了，空白页面了,您可以试一下，控制台有报错了，报的错我就不贴了

但是如果我不起服务，直接用浏览器打开`index.html`页面 是可以的没有问题的

**Comment by suxiaoxin** [comment]
npm run start 是用来启动开发服务的，请打开 dev.html 调试
