### ISSUE TITLE
`npm install`的文件能否是bulid过的?

### ISSUE THREAD

**Issue by martin-liu** [YMFE/json-schema-editor-visual#2]
感谢开源这个项目!

不过我尝试使用时发现你们的source code和我的project配置有冲突，所以想请问一下，能不能publish build过的文件到npm而不是source code?

以下是详细版本:

---
react/babel/webpack这一套配置太烦人了，尤其是一大堆插件动不动就有兼容性问题，然后大家又喜欢再封装一层自己的东西。。

结果就是，我打算在某个project用这个库，但是因为配置问题失败了。

在我的project里，`transform-class-properties`和`react-hot-loader`疑似有冲突，当然也可能是其它问题，总之症状就是hot load的时候class里的`static xxx = {}`这种code过不了编译，debug了好久也没能解决。

当然，这不是这个project的问题。不过，如果你们publish到npm的code是build过的，就万事大吉了:laughing:

**Comment by suxiaoxin** [comment]
我回头研究下，暂时还不清楚怎么只编译一部分代码

**Comment by suxiaoxin** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/17695103/38539949-c776bc3a-3ccc-11e8-8c1a-17c285cf9e1a.png)

**Comment by martin-liu** [comment]
cool, thx! 👍
