### ISSUE TITLE
不能设置默认值

### ISSUE THREAD

**Issue by 18boys** [YMFE/json-schema-editor-visual#5]
有的时候,我们可能需要设置下skeme的默认值,比如说 默认让 key为必填项,能加入这种设置默认值的配置么

**Comment by nolanlee** [comment]
![image](https://user-images.githubusercontent.com/3119773/40645744-d69c03ba-6359-11e8-9ab2-ad87473fba40.png)

**Comment by 18boys** [comment]
可能你没听懂我的意思.  我的意思是, 我新建一个key默认是 选中必填, 或者 默认comment写上 '这是备注' 等这种默认值.    背景就是, 我在对yapi二次开发的时候,需要新增的key默认是必填.

**Comment by hellosean1025** [comment]
目前不支持 @18boys
