### ISSUE TITLE
Can we have a live demo?

### ISSUE THREAD

**Issue by DanielYWoo** [YMFE/json-schema-editor-visual#51]
If you put a live demo somewhere to help us evaluate the UX, it would be great!

**Comment by ZPiDER666** [comment]
the demo is here: https://hellosean1025.github.io/json-schema-visual-editor/

**Comment by DanielYWoo** [comment]
hopefully somebody can put it to the README. Thanks!

**Comment by ZPiDER666** [comment]
it is up there in the project description - took me a while to see too :)
