### ISSUE TITLE
是不是可以加一个enum字段

### ISSUE THREAD

**Issue by TesterQiao** [YMFE/json-schema-editor-visual#6]
"enum": [
    422，“sa”
   ]
把接口必须返回的字段加进去

**Comment by hellosean1025** [comment]
字符串类型的字段，点击高级设置，支持枚举

**Comment by TesterQiao** [comment]
http://yapi.demo.qunar.com/editor/
这个url里的转换没有出现

**Comment by gaoxiaomumu** [comment]
那里面的版本不是最新的所以没有
